# Generated by Django 5.1 on 2024-11-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_profile',
            name='photo',
            field=models.ImageField(default='media\\media\\download (1).jpg', null=True, upload_to='media/'),
        ),
    ]
