# Generated by Django 5.1 on 2024-12-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_customer_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
