# Generated by Django 5.1 on 2024-12-04 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_customer_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_profile',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.CreateModel(
            name='customer_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=True, max_length=50)),
                ('addres', models.TextField(max_length=300)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('current', models.BooleanField(choices=[(True, 'TRUE'), (False, 'FALSE')], default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.customer_profile')),
            ],
        ),
    ]
