# Generated by Django 5.1 on 2024-12-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_customer_profile_photo_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_address',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
    ]
