# Generated by Django 5.1 on 2024-12-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0014_alter_customer_address_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_profile',
            name='addres',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_profile',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor_profile',
            name='seller_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
