# Generated by Django 5.1 on 2024-12-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0015_alter_vendor_profile_addres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_profile',
            name='status',
        ),
        migrations.AlterField(
            model_name='vendor_profile',
            name='addres',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_profile',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='vendor_profile',
            name='seller_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
