# Generated by Django 5.1 on 2024-12-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0016_remove_vendor_profile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
