# Generated by Django 5.1 on 2024-12-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0018_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
