# Generated by Django 5.1 on 2024-12-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0019_category_offer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=100, verbose_name='Coupon Name')),
                ('coupon_id', models.CharField(max_length=50, unique=True, verbose_name='Coupon ID')),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Offer Price')),
                ('min_buy_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Buy Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('validity_date', models.IntegerField(max_length=5)),
                ('validity', models.DateTimeField(verbose_name='Validity')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
    ]
