# Generated by Django 5.1 on 2024-12-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0021_alter_coupon_validity_alter_coupon_validity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
