# Generated by Django 5.1 on 2024-12-09 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0018_category_slug'),
        ('vendor', '0005_products_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveSmallIntegerField(default=1)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.customer_profile')),
                ('poduct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.products')),
            ],
        ),
    ]
