# Generated by Django 5.1 on 2024-12-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='poduct_id',
            new_name='product_id',
        ),
    ]
