# Generated by Django 5.1 on 2024-12-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_poduct_id_cart_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
