# Generated by Django 5.1 on 2024-12-19 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_cart_product_price'),
        ('user_management', '0018_category_slug'),
        ('vendor', '0005_products_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('done', 'Done'), ('refund', 'Refund'), ('no', 'No')], default='no', max_length=10)),
                ('payment_category', models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('online_payment', 'Online Payment')], default='online_payment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.customer_profile')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.vendor_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='null', max_length=15)),
                ('delivery_address', models.TextField(help_text='The address where the order will be delivered.', verbose_name='Delivery Address')),
                ('pincode', models.CharField(help_text='Postal code of the delivery address.', max_length=10, verbose_name='Pincode')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='The total price of the order.', max_digits=10, verbose_name='Total Amount')),
                ('quantity', models.PositiveIntegerField(help_text='The quantity of the product ordered.', verbose_name='Quantity')),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', help_text='The current status of the order.', max_length=20, verbose_name='Order Status')),
                ('created_at', models.DateTimeField(help_text='The date and time when the order was created.', verbose_name='Created At')),
                ('is_ordered', models.BooleanField(default=True, help_text='Indicates whether the order is placed.', verbose_name='Is Ordered')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.customer_profile', verbose_name='Customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.products', verbose_name='product')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.vendor_profile', verbose_name='vendor')),
                ('Payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
