# Generated by Django 5.1 on 2024-12-10 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_cart_product_price'),
        ('user_management', '0018_category_slug'),
        ('vendor', '0005_products_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(help_text='The address where the order will be delivered.', verbose_name='Delivery Address')),
                ('pincode', models.CharField(help_text='Postal code of the delivery address.', max_length=10, verbose_name='Pincode')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='The total price of the order.', max_digits=10, verbose_name='Total Amount')),
                ('quantity', models.PositiveIntegerField(help_text='The quantity of the product ordered.', verbose_name='Quantity')),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', help_text='The current status of the order.', max_length=20, verbose_name='Order Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the order was created.', verbose_name='Created At')),
                ('is_ordered', models.BooleanField(default=True, help_text='Indicates whether the order is placed.', verbose_name='Is Ordered')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.customer_profile', verbose_name='Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.products', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
