# Generated by Django 5.1 on 2024-12-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_cart_product_price_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cat_offer',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_offer',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='cat_offer',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='product_offer',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
