# Generated by Django 5.1 on 2024-12-10 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_order_options_remove_order_product_and_more'),
        ('vendor', '0005_products_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.products', verbose_name='product'),
        ),
    ]
