# Generated by Django 5.1 on 2024-12-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_cart_cat_offer_cart_product_offer_order_cat_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_price',
            field=models.IntegerField(default=0),
        ),
    ]
