# Generated by Django 5.1 on 2024-12-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_order_coupon_id_order_coupon_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_id',
            field=models.CharField(default='0'),
        ),
    ]
