# Generated by Django 5.1 on 2024-12-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='null', max_length=15),
        ),
    ]
