# Generated by Django 5.1 on 2024-12-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(help_text='The date and time when the order was created.', verbose_name='Created At'),
        ),
    ]
