# Generated by Django 5.1 on 2024-12-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_order_coupon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
