# Generated by Django 5.1 on 2024-12-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_category',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('online_payment', 'Online Payment'), ('Wallet', 'Wallet')], default='online_payment', max_length=20),
        ),
    ]
