# Generated by Django 5.1 on 2024-12-29 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_wishlist'),
        ('vendor', '0007_alter_products_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.products'),
        ),
    ]
